### PR TITLE
Adding new image processing function (contrast stretch). 

### PR DESCRIPTION
**Pull request by Salmanshams67**
which is inspired by OpenCV library.

### CODE REVIEW

**Comment by Salmanshams67** [comment]
@targos, @lpatiny, I have raised one PR, please check, it is running on every other version except (12.x), otherwise it is running properly.

**Comment by Salmanshams67** [comment]
@stropitek, @JulDenereaz, @jajoe, @greenkeeperio-bot, @KellyJoha, @andcastillo, please look into this PR request.

**Comment by stropitek** [comment]
There is no need to ping everyone, people like me who are watching the project will get notified even if you don't.

I think to justify adding this to image-js, it has to be a standard algorithm with a standard name. From what I see it's not based on the opencv library but on an opencv tutorial.

I think "contrast stretching" is a generic term used for any method that widens the range of values used by the image's pixels but it could be anything, including non-linear stretching. Therefore I am not in favor of adding this to image-js.

**Comment by Salmanshams67** [comment]
@stropitek, pardon me, about the function name, I shall make the changes accordingly.

**Comment by Salmanshams67** [comment]
@stropitek, Isn't "linearContrastStretch" a more descriptive name that explicitly mentions contrast stretching in a linear manner, or we can use "convertScaleAbs" as openCV. (If you have any other name suggestion, kindly mention).

**Comment by Salmanshams67** [comment]
@stropitek, a gentle reminder.

**Comment by stropitek** [comment]
I think that as is the case for opencv, this should be in a tutorial rather than in the API of image-js, because it is too specific and can already be done in a few lines of code with the current API.


Thank you for your understanding, I'm closing the PR.

**Comment by Salmanshams67** [comment]
Hi Daniel,

What do you mean by tutorial? Please elaborate.

Just leave opencv aside, I want to improve this ImageJS library (I have a
few more image processing functions, which are not there in ImageJS, please
guide me.

Thank you.

**Pull request closed without merging**
